/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.admin;

import controlador.ConfiguracionSistemaController;
import controlador.PrestamosController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelo.Prestamos;

/**
 *
 * @author Hector Marquez
 */
public class GestionDevoluciones extends javax.swing.JFrame {
    
    private final PrestamosController prestamosController;
    private final ConfiguracionSistemaController configuracionController;
    private final DefaultTableModel modeloDevoluciones;

    /**
     * Creates new form GestionDevoluciones
     */
    public GestionDevoluciones() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        prestamosController = new PrestamosController();
        configuracionController = new ConfiguracionSistemaController();
        modeloDevoluciones = new DefaultTableModel(new Object[]{"ID", "Usuario", "Ejemplar", "Fecha Préstamo", "Fecha Devolución", "Estado", "Mora"}, 0);
        tblDevoluciones.setModel(modeloDevoluciones);
        cargarDevoluciones();
        
    }
    
    private void cargarDevoluciones() {
        modeloDevoluciones.setRowCount(0);
        List<Prestamos> prestamos = prestamosController.listarPrestamosConDetalles(); // Todos
        for (Prestamos prestamo : prestamos) {
            modeloDevoluciones.addRow(new Object[]{
                    prestamo.getIdPrestamo(),
                    prestamo.getNombreUsuario(),
                    prestamo.getTituloEjemplar(),
                    prestamo.getFechaPrestamo(),
                    prestamo.getFechaDevolucion(),
                    prestamo.isDevuelto() ? "Devuelto" : "No Devuelto",
                    prestamo.getMora()
            });
        }
    }
    
    private void registrarDevolucion() {
        int filaSeleccionada = tblDevoluciones.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un préstamo para registrar la devolución.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idPrestamo = (int) tblDevoluciones.getValueAt(filaSeleccionada, 0);
        java.sql.Date fechaDevolucion = (java.sql.Date) tblDevoluciones.getValueAt(filaSeleccionada, 4);

        if (fechaDevolucion == null) {
            JOptionPane.showMessageDialog(this, "La fecha de devolución no es válida.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Obtener mora diaria desde la configuración del sistema
        double moraDiaria = configuracionController.obtenerConfiguracion().getMoraDiaria();
        long diasRetraso = (System.currentTimeMillis() - fechaDevolucion.getTime()) / (1000 * 60 * 60 * 24);
        double mora = diasRetraso > 0 ? diasRetraso * moraDiaria : 0.0;

        // Registrar devolución
        if (prestamosController.marcarDevuelto(idPrestamo, mora)) {
            JOptionPane.showMessageDialog(this, "Préstamo marcado como devuelto. Mora aplicada: $" + mora, "Éxito", JOptionPane.INFORMATION_MESSAGE);
            cargarDevoluciones(); // Refrescar la tabla
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar la devolución.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void filtrarPendientes() {
        modeloDevoluciones.setRowCount(0);
        List<Prestamos> pendientes = prestamosController.listarPendientes();
        for (Prestamos prestamo : pendientes) {
            modeloDevoluciones.addRow(new Object[]{
                prestamo.getIdPrestamo(),
                prestamo.getIdUsuario(),
                prestamo.getIdItem(),
                prestamo.getFechaPrestamo(),
                prestamo.getFechaDevolucion(),
                "No Devuelto",
                prestamo.getMora()
            });
        }
    }
    
    private void filtrarPrestamos(String criterio){
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modeloDevoluciones);
        tblDevoluciones.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + criterio));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFiltrarPendientes = new javax.swing.JButton();
        btnActualizarDevoluciones = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDevoluciones = new javax.swing.JTable();
        btnRegistrarDevolucion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnFiltrarPendientes.setText("FILTRAR PENDIENTES");
        btnFiltrarPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarPendientesActionPerformed(evt);
            }
        });

        btnActualizarDevoluciones.setText("ACTUALIZAR TABLA");
        btnActualizarDevoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarDevolucionesActionPerformed(evt);
            }
        });

        tblDevoluciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDevoluciones);

        btnRegistrarDevolucion.setText("REGISTRAR DEVOLUCION");
        btnRegistrarDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarDevolucionActionPerformed(evt);
            }
        });

        jLabel1.setText("BUSCAR");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFiltrarPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizarDevoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRegistrarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFiltrarPendientes)
                    .addComponent(btnActualizarDevoluciones))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnRegistrarDevolucion)
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarDevolucionActionPerformed
        registrarDevolucion();
    }//GEN-LAST:event_btnRegistrarDevolucionActionPerformed

    private void btnFiltrarPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarPendientesActionPerformed
        filtrarPendientes();
    }//GEN-LAST:event_btnFiltrarPendientesActionPerformed

    private void btnActualizarDevolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarDevolucionesActionPerformed
        cargarDevoluciones();
        JOptionPane.showMessageDialog(this, "Tabla de devoluciones actualizada.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnActualizarDevolucionesActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        filtrarPrestamos(txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionDevoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionDevoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionDevoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionDevoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionDevoluciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarDevoluciones;
    private javax.swing.JButton btnFiltrarPendientes;
    private javax.swing.JButton btnRegistrarDevolucion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDevoluciones;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
